# Generated by Django 6.0.1 on 2026-01-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('NOT_DELIVERED', 'Not Delivered'), ('HOLIDAY', 'Holiday')], default='DELIVERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newspaper.newspaper')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.subscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'date'), name='unique_delivery_per_customer_per_day')],
            },
        ),
    ]
